### PR TITLE
Typings for json data

### PR DESCRIPTION
**Pull request by LastDragon-ru**
Not sure that this is the best way, maybe will be better create `d.ts` files automatically while json to js conversion, unfortunately, I'm not sure how to implement this.

### CODE REVIEW

**Comment by catamphetamine** [comment]
This doesn't look good.
First, there's code duplication.
Second, it's unclear why would you require typings for JSON.

**Comment by catamphetamine** [comment]
> I need custom metadata in angular app, without typings is not possible to use it 

No need to `import` the json file: use the `/mobile` subpackage for that.

**Comment by LastDragon-ru** [comment]
> No need to import the json file: use the /mobile subpackage for that.

but mobile will use `metadata.mobile.json.js`, right? I need `full` and I also need direct access to metadata

```
    public getCountryCallingCode(country: Country | string): string | null {
        const data = this.metadata.countries[this.getCountryCode(country)] || null;
        const code = data ? data[0] : null;

        return code;
    }
```

**Comment by catamphetamine** [comment]
> mobile will use metadata.mobile.json.js, right?

It will.

> and I also need direct access to metadata

That's your issues.

**Comment by LastDragon-ru** [comment]
> That's your issues.

Nope. Without these typings [custom metadata](https://github.com/catamphetamine/libphonenumber-js#customizing-metadata) cannot be used in ts.

**Comment by catamphetamine** [comment]
> Nope. Without these typings custom metadata cannot be used in ts.

Show how it can't be used and what's the error message.

**Comment by LastDragon-ru** [comment]
> Show how it can't be used and what's the error message.

Error will be the same as https://github.com/catamphetamine/libphonenumber-js/issues/239#issuecomment-494474677

image

Typescript cannot import js without definitions. Of course, it can be solved by hand but much better when you no need additional work to use the library.

**Comment by LastDragon-ru** [comment]
> Typescript cannot import js without definitions.

So  `MetadataJson` (and `ExamplesJson`) type required in any case. The `*.json.d.ts` probably will be better to generate while json->js conversion.

**Comment by LastDragon-ru** [comment]
> Paste the code that results in the error.

```ts
import { Component } from '@angular/core';
import {parsePhoneNumberFromString} from 'libphonenumber-js/core';
import metadata from 'libphonenumber-js/metadata.min.json.js';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  name = 'Angular';

  test() {
    const parsed = parsePhoneNumberFromString('+7 495 441 12 34', metadata);
    const valid  = parsed != null && parsed.isValid();

    return valid;
  }
}
```

image

Full source
[angular-1saffi.zip](https://github.com/catamphetamine/libphonenumber-js/files/3409714/angular-1saffi.zip)

**Comment by catamphetamine** [comment]
Why would you import `metadata.min.json` manually.

**Comment by LastDragon-ru** [comment]
> Why would you import metadata.min.json manually.

Because I need some additional data from metadata? Eg country calling code to output it for user.

**Comment by catamphetamine** [comment]
Use this instead.
https://github.com/catamphetamine/libphonenumber-js/blob/9ec9103b9029ac77ad0ac09c8cbc60c18da0ef35/min/index.d.ts#L49

**Comment by LastDragon-ru** [comment]
> Use this instead.

Ok, thanks. Any way to access to `country_calling_codes` to find a country by one number? ("+1" - US, "+7" - RU, etc)

**Comment by catamphetamine** [comment]
> Any way to access to country_calling_codes to find a country by one number? ("+1" - US, "+7" - RU, etc)

Multiple countries have the same prefixes.

**Comment by LastDragon-ru** [comment]
> Multiple countries have the same prefixes.

I know. But I need same behavior like https://intl-tel-input.com/ (+7 will ru, not kz)

**Comment by catamphetamine** [comment]
> I know. But I need same behavior like https://intl-tel-input.com/ (+7 will ru, not kz)

`+7` is both for RU and KZ.

**Comment by LastDragon-ru** [comment]
> +7 is both for RU and KZ.

Check the example please

**Comment by catamphetamine** [comment]
> Check the example please

No, you check.

**Pull request closed without merging**
