### PR TITLE
Add isValidNumberForRegion() to declaration files

### PR DESCRIPTION
**Pull request by msheakoski**

### CODE REVIEW

**Comment by catamphetamine** [comment]
Add also to `index.d.ts`

**Comment by msheakoski** [comment]
@catamphetamine Thank you for pointing that out. The declaration for index.d.ts has been added.

**Comment by catamphetamine** [comment]
@msheakoski thx, merged, will release today and post here.

**Comment by catamphetamine** [comment]
Released `libphonenumber-js@1.3.2`.

**Pull request merged**
