### PR TITLE
Upgrade to babel 7

### PR DESCRIPTION
**Pull request by TrySound**
```diff
- 140     bundle/libphonenumber-js.min.js
+ 132     bundle/libphonenumber-js.min.js
- 192     bundle/libphonenumber-max.js
+ 184     bundle/libphonenumber-max.js
- 132     bundle/libphonenumber-min.js
+ 124     bundle/libphonenumber-min.js
- 160     bundle/libphonenumber-mobile.js
+ 148     bundle/libphonenumber-mobile.js
```

### CODE REVIEW

**Comment by catamphetamine** [comment]
I don't see the `rest-spread` plugin in your config.
I also don't see the `for-of` transform in your config.
Use this one as a reference:
https://github.com/catamphetamine/chartogram/blob/master/.babelrc

**Comment by TrySound** [comment]
object-rest-spread is part of spec. No need for plugin.

Maybe enable loose mode for whole env preset?

**Comment by catamphetamine** [comment]
> Maybe enable loose mode for whole env preset?

The thing is: the library is compiled and used in any environment.
`for of` requires a Polyfill for `Symbol`: open any file in `modules`, for example, and see the transpiled `for of` statement: it will require `Symbol.iterator`.
This would break applications using old environment like old Node.js or Internet Explorer which is unacceptable.
So, you'll have to make sure that `...` spread is transpiled and that `for of` is transpiled without needing `Symbol.iterator` to work (you can see how Babel 5 does it with `if Array.isArray(...) then ... else Symbol.iterator`.
After you've checked that these 2 cases work then the PR could be merged.

**Comment by catamphetamine** [comment]
> Maybe enable loose mode for whole env preset?

Then it would ponetially come with other surprises and Babel 5 config would be better in that case.

**Comment by catamphetamine** [comment]
> object-rest-spread is part of spec. No need for plugin.

Provide a proof of that.

**Comment by TrySound** [comment]
> Provide a proof of that.

https://github.com/tc39/proposal-object-rest-spread#status-of-this-proposal
Also build is done without errors.

**Comment by catamphetamine** [comment]
> https://github.com/tc39/proposal-object-rest-spread#status-of-this-proposal
Also build is done without errors.

Well, I'm not convinced.
`react-create-app` still uses it:
https://github.com/facebook/create-react-app/blob/master/packages/babel-preset-react-app/create.js#L157
I guess we'll use it until they stop using it.
So you should add it too.

**Comment by catamphetamine** [comment]
See the issue for the rest spread plugin status:
https://github.com/babel/babel/issues/10105

**Comment by catamphetamine** [comment]
See the issue for the rest spread plugin status:
https://github.com/babel/babel/issues/10105

**Comment by TrySound** [comment]
It's used there. I made the same in dozens of projects. babel-preset-env covers it.
https://github.com/babel/babel/blob/master/packages/babel-preset-env/src/available-plugins.js#L40

create-react-app is not the source of truth. They could missed this.

**Comment by catamphetamine** [comment]
Now that's the proof.
Ok, I'll merge and test the PR when I have time.

**Pull request merged**
