### PR TITLE
Meta data Params updates

### PR DESCRIPTION
**Pull request by waleedarshad**
Hi @catamphetamine Please use this merge request to update optional parameters

I had uncommented **es6** & **metadata.min** from my fork **.gitignore** because it was required in code when i included that into my project.

But this pull request is refined form without es6 and metaData. you can merge this

Thanks

### CODE REVIEW

**Comment by catamphetamine** [comment]
The default `parseNumber()` export doesn't accept `metadata`.
The `custom.js` ones do.

**Comment by waleedarshad** [comment]
so for using CustomParseNumber do i have to import like this?

import { parseNumber } from 'libphonenumber-js/custom'

as there is not documentation specified how to use custom methods

**Comment by catamphetamine** [comment]
There is

**Comment by waleedarshad** [comment]
Thanks

**Pull request closed without merging**
